\c bookstore

INSERT INTO books (title, author_last, author_first, genre, publisher) VALUES
  ('Fundamentals of Wavelets', 'Goswami', 'Jaideva', 'signal_processing', 'Wiley'),
  ('Data Smart', 'Foreman', 'John', 'data_science', 'Wiley'),
  ('God Created the Integers', 'Hawking', 'Stephen', 'mathematics', 'Penguin'),
  ('Superfreakonomics', 'Dubner', 'Stephen', 'economics', 'HarperCollins'),
  ('Orientalism', 'Said', 'Edward', 'history', 'Penguin'),
  ('The Nature of Statistical Learning Theory', 'Vapnik', 'Vladimir', 'data_science', 'Springer'),
  ('Integration of the Indian States', 'Menon', 'V P', 'history', 'Orient Blackswan'),
  ('The Drunkard''s Walk', 'Mlodinow', 'Leonard', 'science', 'Penguin'),
  ('Image Processing & Mathematical Morphology', 'Shih', 'Frank', 'signal_processing', 'CRC'),
  ('How to Think Like Sherlock Holmes', 'Konnikova', 'Maria', 'psychology', 'Penguin'),
  ('Data Scientists at Work', 'Gutierrez', 'Sebastian', 'data_science', 'Apress'),
  ('Slaughterhouse Five', 'Vonnegut', 'Kurt', 'fiction', 'Random House'),
  ('Birth of a Theorem', 'Villani', 'Cedric', 'mathematics', 'Bodley Head'),
  ('Structure & Interpretation of Computer Programs', 'Sussman', 'Gerald', 'computer_science', 'MIT Press'),
  ('The Age of Wrath', 'Eraly', 'Abraham', 'history', 'Penguin'),
  ('The Trial', 'Kafka', 'Frank', 'fiction', 'Random House'),
  ('Statistical Decision Theory', 'Pratt', 'John', 'data_science', 'MIT Press'),
  ('Data Mining Handbook', 'Nisbet', 'Robert', 'data_science', 'Apress'),
  ('The New Machiavelli', 'Wells', 'H. G.', 'fiction', 'Penguin'),
  ('Physics & Philosophy', 'Heisenberg', 'Werner', 'science', 'Penguin'),
  ('Making Software', 'Oram', 'Andy', 'computer_science', 'O''Reilly'),
  ('Analysis, Vol I', 'Tao', 'Terence', 'mathematics', 'HBA'),
  ('Machine Learning for Hackers', 'Conway', 'Drew', 'data_science', 'O''Reilly'),
  ('The Signal and the Noise', 'Silver', 'Nate', 'data_science', 'Penguin'),
  ('Python for Data Analysis', 'McKinney', 'Wes', 'data_science', 'O''Reilly'),
  ('Introduction to Algorithms', 'Cormen', 'Thomas', 'computer_science', 'MIT Press'),
  ('The Beautiful and the Damned', 'Deb', 'Siddhartha', 'nonfiction', 'Penguin'),
  ('The Outsider', 'Camus', 'Albert', 'fiction', 'Penguin'),
  ('The Complete Sherlock Holmes - Vol I', 'Doyle', 'Arthur Conan', 'fiction', 'Random House'),
  ('The Complete Sherlock Holmes - Vol II', 'Doyle', 'Arthur Conan', 'fiction', 'Random House'),
  ('The Wealth of Nations', 'Smith', 'Adam', 'economics', 'Random House'),
  ('The Pillars of the Earth', 'Follett', 'Ken', 'fiction', 'Random House'),
  ('Mein Kampf', 'Hitler', 'Adolf', 'nonfiction', 'Rupa'),
  ('The Tao of Physics', 'Capra', 'Fritjof', 'science', 'Penguin'),
  ('Surely You''re Joking Mr Feynman', 'Feynman', 'Richard', 'science', 'Random House'),
  ('A Farewell to Arms', 'Hemingway', 'Ernest', 'fiction', 'Rupa'),
  ('The Veteran', 'Forsyth', 'Frederick', 'fiction', 'Transworld'),
  ('False Impressions', 'Archer', 'Jeffery', 'fiction', 'Pan'),
  ('The Last Lecture', 'Pausch', 'Randy', 'nonfiction', 'Hyperion'),
  ('Return of the Primitive', 'Rand', 'Ayn', 'philosophy', 'Penguin'),
  ('Jurassic Park', 'Crichton', 'Michael', 'fiction', 'Random House'),
  ('A Russian Journal', 'Steinbeck', 'John', 'nonfiction', 'Penguin'),
  ('Tales of Mystery and Imagination', 'Poe', 'Edgar Allen', 'fiction', 'HarperCollins'),
  ('Freakonomics', 'Dubner', 'Stephen', 'economics', 'Penguin'),
  ('The Hidden Connections', 'Capra', 'Fritjof', 'science', 'HarperCollins'),
  ('The Story of Philosophy', 'Durant', 'Will', 'philosophy', 'Pocket'),
  ('Asami Asami', 'Deshpande', 'P L', 'fiction', 'Mauj'),
  ('Journal of a Novel', 'Steinbeck', 'John', 'fiction', 'Penguin'),
  ('Once There Was a War', 'Steinbeck', 'John', 'nonfiction', 'Penguin'),
  ('The Moon is Down', 'Steinbeck', 'John', 'fiction', 'Penguin'),
  ('The Brethren', 'Grisham', 'John', 'fiction', 'Random House'),
  ('In a Free State', 'Naipaul', 'V. S.', 'fiction', 'Rupa'),
  ('Catch 22', 'Heller', 'Joseph', 'fiction', 'Random House'),
  ('The Complete Mastermind', 'BBC', '', 'nonfiction', 'BBC'),
  ('Dylan on Dylan', 'Dylan', 'Bob', 'nonfiction', 'Random House'),
  ('Soft Computing & Intelligent Systems', 'Gupta', 'Madan', 'data_science', 'Elsevier'),
  ('Textbook of Economic Theory', 'Stonier', 'Alfred', 'economics', 'Pearson'),
  ('Econometric Analysis', 'Greene', 'W. H.', 'economics', 'Pearson'),
  ('Learning OpenCV', 'Bradsky', 'Gary', 'data_science', 'O''Reilly'),
  ('Data Structures Using C & C++', 'Tanenbaum', 'Andrew', 'computer_science', 'Prentice Hall'),
  ('Computer Vision, A Modern Approach', 'Forsyth', 'David', 'data_science', 'Pearson'),
  ('Principles of Communication Systems', 'Taub', 'Schilling', 'computer_science', 'TMH'),
  ('Let Us C', 'Kanetkar', 'Yashwant', 'computer_science', 'Prentice Hall'),
  ('The Amulet of Samarkand', 'Stroud', 'Jonathan', 'fiction', 'Random House'),
  ('Crime and Punishment', 'Dostoevsky', 'Fyodor', 'fiction', 'Penguin'),
  ('Angels & Demons', 'Brown', 'Dan', 'fiction', 'Random House'),
  ('The Argumentative Indian', 'Sen', 'Amartya', 'nonfiction', 'Picador'),
  ('Sea of Poppies', 'Ghosh', 'Amitav', 'fiction', 'Penguin'),
  ('The Idea of Justice', 'Sen', 'Amartya', 'nonfiction', 'Penguin'),
  ('A Raisin in the Sun', 'Hansberry', 'Lorraine', 'fiction', 'Penguin'),
  ('All the President''s Men', 'Woodward', 'Bob', 'history', 'Random House'),
  ('A Prisoner of Birth', 'Archer', 'Jeffery', 'fiction', 'Pan'),
  ('Scoop!', 'Nayar', 'Kuldip', 'history', 'HarperCollins'),
  ('Ahe Manohar Tari', 'Deshpande', 'Sunita', 'nonfiction', 'Mauj'),
  ('The Last Mughal', 'Dalrymple', 'William', 'history', 'Penguin'),
  ('Social Choice & Welfare, Vol 39 No. 1', 'Authors', 'Various', 'economics', 'Springer'),
  ('Radiowaril Bhashane & Shrutika', 'Deshpande', 'P L', 'nonfiction', 'Mauj'),
  ('Gun Gayin Awadi', 'Deshpande', 'P L', 'nonfiction', 'Mauj'),
  ('Aghal Paghal', 'Deshpande', 'P L', 'nonfiction', 'Mauj'),
  ('Maqta-e-Ghalib', 'Garg', 'Sanjay', 'fiction', 'Mauj'),
  ('Beyond Degrees', '', '', 'nonfiction', 'HarperCollins'),
  ('Manasa', 'Kale', 'V P', 'nonfiction', 'Mauj'),
  ('India from Midnight to Milennium', 'Tharoor', 'Shashi', 'history', 'Penguin'),
  ('The World''s Greatest Trials', '', '', 'history', ''),
  ('The Great Indian Novel', 'Tharoor', 'Shashi', 'fiction', 'Penguin'),
  ('O Jerusalem!', 'Lapierre', 'Dominique', 'history', 'vikas'),
  ('The City of Joy', 'Lapierre', 'Dominique', 'fiction', 'vikas'),
  ('Freedom at Midnight', 'Lapierre', 'Dominique', 'history', 'vikas'),
  ('The Winter of Our Discontent', 'Steinbeck', 'John', 'fiction', 'Penguin'),
  ('On Education', 'Russell', 'Bertrand', 'philosophy', 'Routledge'),
  ('Free Will', 'Harris', 'Sam', 'philosophy', 'FreePress'),
  ('Bookless in Baghdad', 'Tharoor', 'Shashi', 'nonfiction', 'Penguin'),
  ('The Case of the Lame Canary', 'Gardner', 'Earle Stanley', 'fiction', ''),
  ('The Theory of Everything', 'Hawking', 'Stephen', 'science', 'Jaico'),
  ('New Markets & Other Essays', 'Drucker', 'Peter', 'economics', 'Penguin'),
  ('Electric Universe', 'Bodanis', 'David', 'science', 'Penguin'),
  ('The Hunchback of Notre Dame', 'Hugo', 'Victor', 'fiction', 'Random House'),
  ('Burning Bright', 'Steinbeck', 'John', 'fiction', 'Penguin'),
  ('The Age of Discontuinity', 'Drucker', 'Peter', 'economics', 'Random House'),
  ('Doctor in the Nude', 'Gordon', 'Richard', 'fiction', 'Penguin'),
  ('Down and Out in Paris & London', 'Orwell', 'George', 'nonfiction', 'Penguin'),
  ('Identity & Violence', 'Sen', 'Amartya', 'philosophy', 'Penguin'),
  ('Beyond the Three Seas', 'Dalrymple', 'William', 'history', 'Random House'),
  ('The World''s Greatest Short Stories', '', '', 'fiction', 'Jaico'),
  ('Talking Straight', 'Iacoca', 'Lee', 'nonfiction', ''),
  ('Maugham''s Collected Short Stories, Vol 3', 'Maugham', 'William S', 'fiction', 'Vintage'),
  ('The Phantom of Manhattan', 'Forsyth', 'Frederick', 'fiction', ''),
  ('Ashenden of The British Agent', 'Maugham', 'William S', 'fiction', 'Vintage'),
  ('Zen & The Art of Motorcycle Maintenance', 'Pirsig', 'Robert', 'philosophy', 'Vintage'),
  ('The Great War for Civilization', 'Fisk', 'Robert', 'history', 'HarperCollins'),
  ('We the Living', 'Rand', 'Ayn', 'fiction', 'Penguin'),
  ('The Artist and the Mathematician', 'Aczel', 'Amir', 'science', 'HighStakes'),
  ('History of Western Philosophy', 'Russell', 'Bertrand', 'philosophy', 'Routledge'),
  ('Selected Short Stories', '', '','fiction', 'Jaico'),
  ('Rationality & Freedom', 'Sen', 'Amartya', 'economics', 'Springer'),
  ('Clash of Civilizations and Remaking of the World Order', 'Huntington', 'Samuel', 'history', 'Simon & Schuster'),
  ('Uncommon Wisdom', 'Capra', 'Fritjof', 'nonfiction', 'Fontana'),
  ('One', 'Bach', 'Richard', 'nonfiction', 'Dell'),
  ('Karl Marx Biography', '', '', 'nonfiction', ''),
  ('To Sir With Love', 'Braithwaite', '', 'fiction', 'Penguin'),
  ('Half A Life', 'Naipaul', 'V S', 'fiction', ''),
  ('The Discovery of India', 'Nehru', 'Jawaharlal', 'history', ''),
  ('Apulki', 'Deshpande', 'P L', 'nonfiction', ''),
  ('Unpopular Essays', 'Russell', 'Bertrand', 'philosophy', ''),
  ('The Deceiver', 'Forsyth', 'Frederick', 'fiction', ''),
  ('Veil: Secret Wars of the CIA', 'Woodward', 'Bob', 'history', ''),
  ('Char Shabda', 'Deshpande', 'P L', 'nonfiction', ''),
  ('Rosy is My Relative', 'Durrell', 'Gerald', 'fiction', ''),
  ('The Moon and Sixpence', 'Maugham', 'William S', 'fiction', ''),
  ('Political Philosophers', '', '', 'philosophy', ''),
  ('A Short History of the World', 'Wells', 'H G', 'history', ''),
  ('The Trembling of a Leaf', 'Maugham', 'William S', 'fiction', ''),
  ('Doctor on the Brain', 'Gordon', 'Richard', 'fiction', ''),
  ('Simpsons & Their Mathematical Secrets', 'Singh', 'Simon', 'science', ''),
  ('Pattern Classification', 'Duda', 'Hart', 'data_science', ''),
  ('From Beirut to Jerusalem', 'Friedman', 'Thomas', 'history', ''),
  ('The Code Book', 'Singh', 'Simon', 'science', ''),
  ('The Age of the Warrior', 'Fisk', 'Robert', 'history', ''),
  ('Final Crisis', '', '', 'comic', ''),
  ('The Killing Joke', '', '', 'comic', ''),
  ('Flashpoint', '', '', 'comic', ''),
  ('Batman Earth One', '', '', 'comic', ''),
  ('Crisis on Infinite Earths', '', '', 'comic', ''),
  ('The Numbers Behind Numb3rs', 'Devlin', 'Keith', 'science', ''),
  ('Superman Earth One - 1', '', '', 'comic', ''),
  ('Superman Earth One - 2', '', '', 'comic', ''),
  ('Justice League: Throne of Atlantis', '', '', 'comic', ''),
  ('Justice League: The Villain''s Journey', '', '', 'comic', ''),
  ('The Death of Superman', '', '', 'comic', ''),
  ('History of the DC Universe', '', '', 'comic', ''),
  ('Batman: The Long Halloween', '', '', 'comic', ''),
  ('A Life in Letters', 'Steinbeck', 'John', 'nonfiction', ''),
  ('The Information', 'Gleick', 'James', 'science', ''),
  ('Journal of Economics, vol 106 No 3', '', '', 'economics', ''),
  ('Elements of Information Theory', 'Thomas', 'Joy', 'data_science', ''),
  ('Power Electronics - Rashid', 'Rashid', 'Muhammad', 'computer_science', ''),
  ('Power Electronics - Mohan', 'Mohan', 'Ned', 'computer_science', ''),
  ('Neural Networks', 'Haykin', 'Simon', 'data_science', ''),
  ('The Grapes of Wrath', 'Steinbeck', 'John', 'fiction', ''),
  ('Vyakti ani Valli', 'Deshpande', 'P L', 'nonfiction', ''),
  ('Statistical Learning Theory', 'Vapnik', 'Vladimir', 'data_science', ''),
  ('Empire of the Mughal - The Tainted Throne', 'Rutherford', 'Alex', 'history', ''),
  ('Empire of the Mughal - Brothers at War', 'Rutherford', 'Alex', 'history', ''),
  ('Empire of the Mughal - Ruler of the World', 'Rutherford', 'Alex', 'history', ''),
  ('Empire of the Mughal - The Serpent''s Tooth', 'Rutherford', 'Alex', 'history', ''),
  ('Empire of the Mughal - Raiders from the North', 'Rutherford', 'Alex', 'history', ''),
  ('Mossad', 'Baz-Zohar', 'Michael', 'history', ''),
  ('Jim Corbett Omnibus', 'Corbett', 'Jim', 'nonfiction', ''),
  ('20000 Leagues Under the Sea', 'Verne', 'Jules', 'fiction', ''),
  ('Batatyachi Chal', 'Deshpande', 'P L', 'fiction', ''),
  ('Hafasavnuk', 'Deshpande', 'P L', 'fiction', ''),
  ('Urlasurla', 'Deshpande', 'P L', 'fiction', ''),
  ('Pointers in C', 'Kanetkar', 'Yashwant', 'computer_science', ''),
  ('The Cathedral and the Bazaar', 'Raymond', 'Eric', 'computer_science', ''),
  ('Design with OpAmps', 'Franco', 'Sergio', 'computer_science', ''),
  ('Think Complexity', 'Downey', 'Allen', 'data_science', ''),
  ('The Devil''s Advocate', 'West', 'Morris', 'fiction', ''),
  ('Ayn Rand Answers', 'Rand', 'Ayn', 'philosophy', ''),
  ('Philosophy: Who Needs It', 'Rand', 'Ayn', 'philosophy', ''),
  ('The World''s Great Thinkers', '', '', 'philosophy', ''),
  ('Data Analysis with Open Source Tools', 'Janert', 'Phillip', 'data_science', ''),
  ('Broca''s Brain', 'Sagan', 'Carl', 'science', ''),
  ('Men of Mathematics', 'Bell', 'E T', 'mathematics', ''),
  ('Oxford book of Modern Science Writing', 'Dawkins', 'Richard', 'science', ''),
  ('Justice, Judiciary and Democracy', 'Ranjan', 'Sudhanshu', 'philosophy', ''),
  ('The Arthashastra', 'Kautiyla', '', 'philosophy', ''),
  ('We the People', 'Palkhivala', '', 'philosophy', ''),
  ('We the Nation', 'Palkhivala', '', 'philosophy', ''),
  ('The Courtroom Genius', 'Sorabjee', '', 'nonfiction', ''),
  ('Dongri to Dubai', 'Zaidi', 'Hussain', 'nonfiction', ''),
  ('History of England, Foundation', 'Ackroyd', 'Peter', 'history', ''),
  ('City of Djinns', 'Dalrymple', 'William', 'history', ''),
  ('India''s Legal System', 'Nariman', '', 'nonfiction', ''),
  ('More Tears to Cry', 'Sassoon', 'Jean', 'fiction', ''),
  ('The Ropemaker', 'Dickinson', 'Peter', 'fiction', ''),
  ('Angels & Demons', 'Brown', 'Dan', 'fiction', ''),
  ('The Judge', '', '', 'fiction', ''),
  ('The Attorney', '', '', 'fiction', ''),
  ('The Prince', 'Machiavelli', '', 'philosophy', ''),
  ('Eyeless in Gaza', 'Huxley', 'Aldous', 'fiction', ''),
  ('Tales of Beedle the Bard', 'Rowling', 'J K', 'fiction', ''),
  ('Girl with the Dragon Tattoo', 'Larsson', 'Steig', 'fiction', ''),
  ('Girl who kicked the Hornet''s Nest', 'Larsson', 'Steig', 'fiction', ''),
  ('Girl who played with Fire', 'Larsson', 'Steig', 'fiction', ''),
  ('Batman Handbook', '', '', 'comic', ''),
  ('Murphy''s Law', '', '', 'nonfiction', ''),
  ('Structure and Randomness', 'Tao', 'Terence', 'mathematics', ''),
  ('Image Processing with MATLAB', 'Eddins', 'Steve', 'signal_processing', ''),
  ('Animal Farm', 'Orwell', 'George', 'fiction', ''),
  ('The Idiot', 'Dostoevsky', 'Fyodor', 'fiction', ''),
  ('A Christmas Carol', 'Dickens', 'Charles', 'fiction', '')
;
